import Button from "@/components/form/ui/button";
import RepositoryCard from "@/components/repository-card";
import PortfolioUpdate from "@/components/shapes/portfolio-update";
import { Repository } from "@/types/github";
import Link from "next/link";
import Script from "next/script";
import { FiMail } from "react-icons/fi";

// const pinnedRepositories = [
//   'snake',
//   'hotkeys',
//   'optical-character-recognition',
//   'virtual-meeting-ui',
//   'decifra-me-js',
//   'ease'
// ]

const repositories: Repository[] = [
  {
    id: 112896649,
    // node_id: 'MDEwOlJlcG9zaXRvcnkxMTI4OTY2NDk=',
    name: "snake",
    // full_name: 'tchesa/snake',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/snake",
    description: "Simple web implementation of the classic snake game.",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/snake',
    // forks_url: 'https://api.github.com/repos/tchesa/snake/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/snake/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/snake/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/snake/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/snake/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/snake/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/snake/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/snake/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/snake/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/snake/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/snake/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/snake/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/snake/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/snake/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/snake/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/snake/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/snake/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/snake/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/snake/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/snake/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/snake/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/snake/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/snake/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/snake/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/snake/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/snake/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/snake/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/snake/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/snake/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/snake/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/snake/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/snake/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/snake/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/snake/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/snake/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/snake/deployments',
    // created_at: '2017-12-03T03:23:24Z',
    // updated_at: '2023-03-29T19:57:34Z',
    // pushed_at: '2018-03-09T13:47:50Z',
    // git_url: 'git://github.com/tchesa/snake.git',
    // ssh_url: 'git@github.com:tchesa/snake.git',
    // clone_url: 'https://github.com/tchesa/snake.git',
    // svn_url: 'https://github.com/tchesa/snake',
    // homepage: 'https://tchesa.github.io/snake/',
    // size: 155,
    stargazers_count: 11,
    // watchers_count: 11,
    language: "JavaScript",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: true,
    // has_discussions: false,
    forks_count: 2,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 0,
    // license: null,
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: [],
    // visibility: 'public',
    // forks: 2,
    // open_issues: 0,
    // watchers: 11,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 2,
    // subscribers_count: 2
  },
  {
    id: 196049501,
    // node_id: 'MDEwOlJlcG9zaXRvcnkxOTYwNDk1MDE=',
    name: "hotkeys",
    // full_name: 'tchesa/hotkeys',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/hotkeys",
    description: "A library to handle keybindings as event triggers",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/hotkeys',
    // forks_url: 'https://api.github.com/repos/tchesa/hotkeys/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/hotkeys/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/hotkeys/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/hotkeys/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/hotkeys/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/hotkeys/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/hotkeys/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/hotkeys/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/hotkeys/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/hotkeys/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/hotkeys/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/hotkeys/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/hotkeys/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/hotkeys/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/hotkeys/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/hotkeys/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/hotkeys/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/hotkeys/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/hotkeys/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/hotkeys/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/hotkeys/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/hotkeys/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/hotkeys/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/hotkeys/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/hotkeys/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/hotkeys/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/hotkeys/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/hotkeys/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/hotkeys/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/hotkeys/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/hotkeys/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/hotkeys/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/hotkeys/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/hotkeys/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/hotkeys/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/hotkeys/deployments',
    // created_at: '2019-07-09T16:56:43Z',
    // updated_at: '2023-03-26T06:14:20Z',
    // pushed_at: '2023-03-21T11:31:51Z',
    // git_url: 'git://github.com/tchesa/hotkeys.git',
    // ssh_url: 'git@github.com:tchesa/hotkeys.git',
    // clone_url: 'https://github.com/tchesa/hotkeys.git',
    // svn_url: 'https://github.com/tchesa/hotkeys',
    // homepage: '',
    // size: 1390,
    stargazers_count: 6,
    // watchers_count: 6,
    language: "TypeScript",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: false,
    // has_discussions: false,
    forks_count: 0,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 2,
    // license: {
    //   key: 'mit',
    //   name: 'MIT License',
    //   spdx_id: 'MIT',
    //   url: 'https://api.github.com/licenses/mit',
    //   node_id: 'MDc6TGljZW5zZTEz'
    // },
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: ['hotkeys', 'keybindings', 'keyboard-shortcuts'],
    // visibility: 'public',
    // forks: 0,
    // open_issues: 2,
    // watchers: 6,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 0,
    // subscribers_count: 0
  },
  {
    id: 141624488,
    // node_id: 'MDEwOlJlcG9zaXRvcnkxNDE2MjQ0ODg=',
    name: "optical-character-recognition",
    // full_name: 'tchesa/optical-character-recognition',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/optical-character-recognition",
    description:
      "Simple implementation of an optical character recognition script using SVM",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/optical-character-recognition',
    // forks_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/optical-character-recognition/deployments',
    // created_at: '2018-07-19T19:51:41Z',
    // updated_at: '2021-01-21T18:17:13Z',
    // pushed_at: '2018-07-28T00:54:44Z',
    // git_url: 'git://github.com/tchesa/optical-character-recognition.git',
    // ssh_url: 'git@github.com:tchesa/optical-character-recognition.git',
    // clone_url: 'https://github.com/tchesa/optical-character-recognition.git',
    // svn_url: 'https://github.com/tchesa/optical-character-recognition',
    // homepage: '',
    // size: 5044,
    stargazers_count: 1,
    // watchers_count: 1,
    language: "Python",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: false,
    // has_discussions: false,
    forks_count: 0,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 1,
    // license: null,
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: ['computer-vision', 'ocr', 'python', 'scikit-learn', 'svm'],
    // visibility: 'public',
    // forks: 0,
    // open_issues: 1,
    // watchers: 1,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 0,
    // subscribers_count: 1
  },
  {
    id: 471013281,
    // node_id: 'R_kgDOHBMXoQ',
    name: "virtual-meeting-ui",
    // full_name: 'tchesa/virtual-meeting-ui',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/virtual-meeting-ui",
    description: "A prototype of web-based virtual meeting app",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui',
    // forks_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/virtual-meeting-ui/deployments',
    // created_at: '2022-03-17T13:46:59Z',
    // updated_at: '2022-06-19T21:17:29Z',
    // pushed_at: '2022-06-19T21:59:29Z',
    // git_url: 'git://github.com/tchesa/virtual-meeting-ui.git',
    // ssh_url: 'git@github.com:tchesa/virtual-meeting-ui.git',
    // clone_url: 'https://github.com/tchesa/virtual-meeting-ui.git',
    // svn_url: 'https://github.com/tchesa/virtual-meeting-ui',
    // homepage: 'https://tchesa.github.io/virtual-meeting-ui/',
    // size: 1737,
    stargazers_count: 1,
    // watchers_count: 1,
    language: "TypeScript",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: true,
    // has_discussions: false,
    forks_count: 1,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 0,
    // license: null,
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: ['conference', 'react', 'sass'],
    // visibility: 'public',
    // forks: 1,
    // open_issues: 0,
    // watchers: 1,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 1,
    // subscribers_count: 1
  },
  {
    id: 613536420,
    // node_id: 'R_kgDOJJHSpA',
    name: "decifra-me-js",
    // full_name: 'tchesa/decifra-me-js',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/decifra-me-js",
    description: "A javascript implementation of a puzzle game.",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/decifra-me-js',
    // forks_url: 'https://api.github.com/repos/tchesa/decifra-me-js/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/decifra-me-js/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/decifra-me-js/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/decifra-me-js/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/decifra-me-js/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/decifra-me-js/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/decifra-me-js/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/decifra-me-js/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/decifra-me-js/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/decifra-me-js/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/decifra-me-js/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/decifra-me-js/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/decifra-me-js/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/decifra-me-js/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/decifra-me-js/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/decifra-me-js/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/decifra-me-js/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/decifra-me-js/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/decifra-me-js/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/decifra-me-js/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/decifra-me-js/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/decifra-me-js/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/decifra-me-js/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/decifra-me-js/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/decifra-me-js/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/decifra-me-js/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/decifra-me-js/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/decifra-me-js/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/decifra-me-js/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/decifra-me-js/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/decifra-me-js/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/decifra-me-js/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/decifra-me-js/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/decifra-me-js/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/decifra-me-js/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/decifra-me-js/deployments',
    // created_at: '2023-03-13T19:05:39Z',
    // updated_at: '2023-03-27T17:03:29Z',
    // pushed_at: '2023-04-07T20:37:46Z',
    // git_url: 'git://github.com/tchesa/decifra-me-js.git',
    // ssh_url: 'git@github.com:tchesa/decifra-me-js.git',
    // clone_url: 'https://github.com/tchesa/decifra-me-js.git',
    // svn_url: 'https://github.com/tchesa/decifra-me-js',
    // homepage: 'https://clever-crumble-85e001.netlify.app/',
    // size: 280,
    stargazers_count: 0,
    // watchers_count: 0,
    language: "TypeScript",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: false,
    // has_discussions: false,
    forks_count: 0,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 0,
    // license: null,
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: [],
    // visibility: 'public',
    // forks: 0,
    // open_issues: 0,
    // watchers: 0,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 0,
    // subscribers_count: 1
  },
  {
    id: 624957549,
    // node_id: 'R_kgDOJUAYbQ',
    name: "ease",
    // full_name: 'tchesa/ease',
    // private: false,
    // owner: {
    //   login: 'tchesa',
    //   id: 10653761,
    //   node_id: 'MDQ6VXNlcjEwNjUzNzYx',
    //   avatar_url: 'https://avatars.githubusercontent.com/u/10653761?v=4',
    //   gravatar_id: '',
    //   url: 'https://api.github.com/users/tchesa',
    //   html_url: 'https://github.com/tchesa',
    //   followers_url: 'https://api.github.com/users/tchesa/followers',
    //   following_url: 'https://api.github.com/users/tchesa/following{/other_user}',
    //   gists_url: 'https://api.github.com/users/tchesa/gists{/gist_id}',
    //   starred_url: 'https://api.github.com/users/tchesa/starred{/owner}{/repo}',
    //   subscriptions_url: 'https://api.github.com/users/tchesa/subscriptions',
    //   organizations_url: 'https://api.github.com/users/tchesa/orgs',
    //   repos_url: 'https://api.github.com/users/tchesa/repos',
    //   events_url: 'https://api.github.com/users/tchesa/events{/privacy}',
    //   received_events_url: 'https://api.github.com/users/tchesa/received_events',
    //   type: 'User',
    //   site_admin: false
    // },
    html_url: "https://github.com/tchesa/ease",
    description: "A tiny javascript easing package with no dependencies.",
    // fork: false,
    // url: 'https://api.github.com/repos/tchesa/ease',
    // forks_url: 'https://api.github.com/repos/tchesa/ease/forks',
    // keys_url: 'https://api.github.com/repos/tchesa/ease/keys{/key_id}',
    // collaborators_url: 'https://api.github.com/repos/tchesa/ease/collaborators{/collaborator}',
    // teams_url: 'https://api.github.com/repos/tchesa/ease/teams',
    // hooks_url: 'https://api.github.com/repos/tchesa/ease/hooks',
    // issue_events_url: 'https://api.github.com/repos/tchesa/ease/issues/events{/number}',
    // events_url: 'https://api.github.com/repos/tchesa/ease/events',
    // assignees_url: 'https://api.github.com/repos/tchesa/ease/assignees{/user}',
    // branches_url: 'https://api.github.com/repos/tchesa/ease/branches{/branch}',
    // tags_url: 'https://api.github.com/repos/tchesa/ease/tags',
    // blobs_url: 'https://api.github.com/repos/tchesa/ease/git/blobs{/sha}',
    // git_tags_url: 'https://api.github.com/repos/tchesa/ease/git/tags{/sha}',
    // git_refs_url: 'https://api.github.com/repos/tchesa/ease/git/refs{/sha}',
    // trees_url: 'https://api.github.com/repos/tchesa/ease/git/trees{/sha}',
    // statuses_url: 'https://api.github.com/repos/tchesa/ease/statuses/{sha}',
    // languages_url: 'https://api.github.com/repos/tchesa/ease/languages',
    // stargazers_url: 'https://api.github.com/repos/tchesa/ease/stargazers',
    // contributors_url: 'https://api.github.com/repos/tchesa/ease/contributors',
    // subscribers_url: 'https://api.github.com/repos/tchesa/ease/subscribers',
    // subscription_url: 'https://api.github.com/repos/tchesa/ease/subscription',
    // commits_url: 'https://api.github.com/repos/tchesa/ease/commits{/sha}',
    // git_commits_url: 'https://api.github.com/repos/tchesa/ease/git/commits{/sha}',
    // comments_url: 'https://api.github.com/repos/tchesa/ease/comments{/number}',
    // issue_comment_url: 'https://api.github.com/repos/tchesa/ease/issues/comments{/number}',
    // contents_url: 'https://api.github.com/repos/tchesa/ease/contents/{+path}',
    // compare_url: 'https://api.github.com/repos/tchesa/ease/compare/{base}...{head}',
    // merges_url: 'https://api.github.com/repos/tchesa/ease/merges',
    // archive_url: 'https://api.github.com/repos/tchesa/ease/{archive_format}{/ref}',
    // downloads_url: 'https://api.github.com/repos/tchesa/ease/downloads',
    // issues_url: 'https://api.github.com/repos/tchesa/ease/issues{/number}',
    // pulls_url: 'https://api.github.com/repos/tchesa/ease/pulls{/number}',
    // milestones_url: 'https://api.github.com/repos/tchesa/ease/milestones{/number}',
    // notifications_url: 'https://api.github.com/repos/tchesa/ease/notifications{?since,all,participating}',
    // labels_url: 'https://api.github.com/repos/tchesa/ease/labels{/name}',
    // releases_url: 'https://api.github.com/repos/tchesa/ease/releases{/id}',
    // deployments_url: 'https://api.github.com/repos/tchesa/ease/deployments',
    // created_at: '2023-04-07T17:29:02Z',
    // updated_at: '2023-04-07T23:45:16Z',
    // pushed_at: '2023-04-10T17:59:08Z',
    // git_url: 'git://github.com/tchesa/ease.git',
    // ssh_url: 'git@github.com:tchesa/ease.git',
    // clone_url: 'https://github.com/tchesa/ease.git',
    // svn_url: 'https://github.com/tchesa/ease',
    // homepage: null,
    // size: 199,
    stargazers_count: 0,
    // watchers_count: 0,
    language: "TypeScript",
    // has_issues: true,
    // has_projects: true,
    // has_downloads: true,
    // has_wiki: true,
    // has_pages: false,
    // has_discussions: false,
    forks_count: 0,
    // mirror_url: null,
    // archived: false,
    // disabled: false,
    // open_issues_count: 0,
    // license: {
    //   key: 'mit',
    //   name: 'MIT License',
    //   spdx_id: 'MIT',
    //   url: 'https://api.github.com/licenses/mit',
    //   node_id: 'MDc6TGljZW5zZTEz'
    // },
    // allow_forking: true,
    // is_template: false,
    // web_commit_signoff_required: false,
    // topics: [],
    // visibility: 'public',
    // forks: 0,
    // open_issues: 0,
    // watchers: 0,
    // default_branch: 'master',
    // temp_clone_token: null,
    // network_count: 0,
    // subscribers_count: 1
  },
];

export default async function Home() {
  // const repositories = await Promise.all<Repository>(pinnedRepositories.map(async name => {
  //   const getRepositoryResponse = await fetch(`https://api.github.com/repos/tchesa/${name}`)
  //   const repositoryData = await getRepositoryResponse.json()
  //   return repositoryData
  // }))

  return (
    <>
      <Script
        id="snitcher-script"
        dangerouslySetInnerHTML={{
          __html: `!function(s,n,i,t,c,h){s.SnitchObject=i;s[i]||(s[i]=function(){
            (s[i].q=s[i].q||[]).push(arguments)});s[i].l=+new Date;c=n.createElement(t);
            h=n.getElementsByTagName(t)[0];c.src='//snid.snitcher.com/8423092.js';
            h.parentNode.insertBefore(c,h)}(window,document,'snid','script');
                
            snid('verify', '8423092');`,
        }}
      />
      <main className="py-4 mb-20 page-layout">
        <div className="flex">
          <div className="pt-[120px] max-w-[500px]">
            <span className="text-xl bg-orange-50">Hi there! I&apos;m</span>
            <span className="font-serif text-5xl text-orange-900 text-shadow-orange-50 block">
              Cesar Lima,
            </span>
            <span className="text-xl bg-orange-50">
              a web developer with expertise in building robust and scalable web
              applications. With expertise in React, Redux, NextJS, Typescript,
              CSS, Sass, Tailwind CSS, I&apos;m able to craft custom solutions
              that meet the unique needs of each project.
            </span>
          </div>
          <div className="grow lg:relative">
            <PortfolioUpdate
              width={600}
              height={600}
              className="hidden md:block opacity-20 lg:opacity-100 absolute top-[10px] lg:top-[-75px] right-0 -z-20"
            />
          </div>
        </div>
        <div className="mt-10 text-center">
          <Link href="/contact">
            <Button type="button">
              <FiMail className="inline mr-2" />
              Send me a message
            </Button>
          </Link>
        </div>
        <h2 className="font-serif font-normal text-2xl mt-10 mb-2 text-shadow-orange-50">
          Pinned repositories
        </h2>
        <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 items-stretch">
          {repositories.map((repository) => (
            <li key={repository.id}>
              <RepositoryCard className="h-full" repository={repository} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
